# Generated by Django 5.2.1 on 2025-05-15 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.models.document


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("passport_number", models.CharField(blank=True, max_length=50)),
                ("student_number", models.CharField(max_length=50)),
                ("current_university", models.CharField(max_length=255)),
                ("current_program", models.CharField(max_length=255)),
                (
                    "current_year",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("destination_university", models.CharField(max_length=255)),
                ("destination_country", models.CharField(max_length=100)),
                ("exchange_program", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                ("motivation_letter", models.TextField(blank=True)),
                ("language_proficiency", models.CharField(blank=True, max_length=100)),
                ("special_requirements", models.TextField(blank=True)),
                ("emergency_contact", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to students)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_review_exchange", "Can review exchange applications"),
                    ("can_approve_exchange", "Can approve exchange applications"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("COORDINATOR", "Exchange Coordinator"),
                            ("MANAGER", "Program Manager"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "permissions": [
                    ("can_verify_users", "Can verify user accounts"),
                    ("can_assign_roles", "Can assign roles to users"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=exchange.models.document.document_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("transcript", "Transcript"),
                            ("motivation_letter", "Motivation Letter"),
                            ("recommendation", "Recommendation Letter"),
                            ("language_cert", "Language Certificate"),
                            ("financial_proof", "Financial Proof"),
                            ("insurance", "Insurance Document"),
                            ("acceptance_letter", "Acceptance Letter"),
                            ("grade_report", "Grade Report"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                (
                    "checksum_algorithm",
                    models.CharField(default="sha256", max_length=10),
                ),
                ("virus_scanned", models.BooleanField(default=False)),
                ("virus_scan_date", models.DateTimeField(blank=True, null=True)),
                ("virus_scan_result", models.CharField(blank=True, max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document is visible to the student",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Document expiration date (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="exchange.exchange",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("can_verify_document", "Can verify documents"),
                    ("can_view_all_documents", "Can view all documents"),
                ],
                "indexes": [
                    models.Index(
                        fields=["exchange", "category"],
                        name="exchange_do_exchang_68801f_idx",
                    ),
                    models.Index(
                        fields=["checksum"], name="exchange_do_checksu_fd7c99_idx"
                    ),
                ],
                "unique_together": {("exchange", "category", "checksum")},
            },
        ),
    ]
