# Generated by Django 5.2.1 on 2025-05-25 23:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import exchange.models.document


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal Note"),
                            ("STUDENT", "Student Visible"),
                            ("OFFICIAL", "Official Communication"),
                        ],
                        default="INTERNAL",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("original_text", models.TextField(blank=True, null=True)),
                ("is_viewed_by_student", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=255)),
                ("host_university", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("credits", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "home_course_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "home_course_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "home_credits",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("APPROVED", "Approved in Learning Agreement"),
                            ("ENROLLED", "Enrolled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                            ("REPLACED", "Replaced"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("term", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["exchange", "course_code"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_grade", models.CharField(max_length=10)),
                (
                    "host_grade_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "converted_grade",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONAL", "Provisional"),
                            ("OFFICIAL", "Official"),
                            ("TRANSFERRED", "Transferred to Home University"),
                        ],
                        default="PROVISIONAL",
                        max_length=20,
                    ),
                ),
                ("date_received", models.DateField()),
                ("date_processed", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["course", "date_received"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic Review"),
                            ("FINANCIAL", "Financial Review"),
                            ("ADMINISTRATIVE", "Administrative Review"),
                            ("FINAL", "Final Decision"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("CONDITIONALLY_APPROVED", "Conditionally Approved"),
                            ("REJECTED", "Rejected"),
                            ("DEFERRED", "Deferred"),
                            ("MORE_INFO", "More Information Needed"),
                        ],
                        max_length=25,
                    ),
                ),
                ("comments", models.TextField()),
                ("conditions", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("is_revised", models.BooleanField(default=False)),
                ("revised_at", models.DateTimeField(blank=True, null=True)),
                ("revision_reason", models.TextField(blank=True, null=True)),
                (
                    "previous_decision",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Status Change"),
                            ("DOCUMENT_UPLOAD", "Document Uploaded"),
                            ("DOCUMENT_APPROVED", "Document Approved"),
                            ("DOCUMENT_REJECTED", "Document Rejected"),
                            ("REVIEW_ADDED", "Review Added"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("REMINDER_SENT", "Reminder Sent"),
                            ("DEADLINE_CHANGED", "Deadline Changed"),
                            ("APPLICATION_EDITED", "Application Edited"),
                            ("ASSIGNMENT_CHANGED", "Assignment Changed"),
                            ("COURSE_ADDED", "Course Added"),
                            ("COURSE_APPROVED", "Course Approved"),
                            ("GRADE_ADDED", "Grade Added"),
                            ("GRADE_TRANSFERRED", "Grade Transferred"),
                            ("MILESTONE", "Milestone Reached"),
                            ("OTHER", "Other Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "previous_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("is_system_generated", models.BooleanField(default=False)),
                ("additional_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Workflow Log",
                "verbose_name_plural": "Workflow Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [("can_verify_documents", "Can verify documents")],
            },
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="exchange_do_exchang_68801f_idx",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="exchange_do_checksu_fd7c99_idx",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="is_verified",
            new_name="verified",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="verification_date",
            new_name="verified_at",
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="document",
            name="file_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash for integrity verification",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="exchange.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="time", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("passport", "Passport Copy"),
                    ("transcript", "Academic Transcript"),
                    ("language_cert", "Language Certificate"),
                    ("motivation_letter", "Motivation Letter"),
                    ("recommendation", "Recommendation Letter"),
                    ("cv", "Curriculum Vitae"),
                    ("photo", "ID Photo"),
                    ("acceptance_letter", "Acceptance Letter"),
                    ("learning_agreement", "Learning Agreement"),
                    ("health_insurance", "Health Insurance"),
                    ("visa", "Visa/Residence Permit"),
                    ("housing_proof", "Housing Proof"),
                    ("financial_support", "Financial Support Proof"),
                    ("grade_sheet", "Grade Sheet"),
                    ("progress_report", "Progress Report"),
                    ("other", "Other Document"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=exchange.models.document.document_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="exchange.exchange",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="exchange.exchange",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="exchange.course",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="grade_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="exchange.document",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="exchange.exchange",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="exchange.exchange",
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="related_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="exchange.comment",
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="exchange.course",
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="related_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="exchange.document",
            ),
        ),
        migrations.AddField(
            model_name="timeline",
            name="related_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events",
                to="exchange.review",
            ),
        ),
        migrations.AddField(
            model_name="workflowlog",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_logs",
                to="exchange.exchange",
            ),
        ),
        migrations.AddField(
            model_name="workflowlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="document",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="document",
            name="checksum_algorithm",
        ),
        migrations.RemoveField(
            model_name="document",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="document",
            name="mime_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="original_filename",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="verification_notes",
        ),
        migrations.RemoveField(
            model_name="document",
            name="virus_scan_date",
        ),
        migrations.RemoveField(
            model_name="document",
            name="virus_scan_result",
        ),
        migrations.RemoveField(
            model_name="document",
            name="virus_scanned",
        ),
        migrations.AddIndex(
            model_name="timeline",
            index=models.Index(
                fields=["exchange", "event_type"], name="exchange_ti_exchang_ee5856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeline",
            index=models.Index(
                fields=["timestamp"], name="exchange_ti_timesta_cbd839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowlog",
            index=models.Index(
                fields=["exchange"], name="exchange_wo_exchang_8ac121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowlog",
            index=models.Index(
                fields=["timestamp"], name="exchange_wo_timesta_59f196_idx"
            ),
        ),
    ]
