# Generated by Django 5.2.1 on 2025-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_phase3_bulk_actions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bulkaction",
            new_name="exchange_bu_action__854ad6_idx",
            old_name="exchange_bu_action__4f7e2d_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkaction",
            new_name="exchange_bu_perform_8ca446_idx",
            old_name="exchange_bu_perform_9a1c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkaction",
            new_name="exchange_bu_status_a3e4b1_idx",
            old_name="exchange_bu_status_d2e5a3_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkactionitem",
            new_name="exchange_bu_bulk_ac_c8bb58_idx",
            old_name="exchange_bu_bulk_ac_0c8b5a_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkactionitem",
            new_name="exchange_bu_exchang_667250_idx",
            old_name="exchange_bu_exchang_47e4c1_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkactionlog",
            new_name="exchange_bu_bulk_ac_50cd70_idx",
            old_name="exchange_bu_bulk_ac_c89c5d_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkactionlog",
            new_name="exchange_bu_level_0a460d_idx",
            old_name="exchange_bu_level_5c9a0f_idx",
        ),
        migrations.AddField(
            model_name="exchange",
            name="advisor_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="exchange",
            name="advisor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exchange",
            name="application_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exchange",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="exchange",
            name="home_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exchange",
            name="scholarship_status",
            field=models.BooleanField(default=False),
        ),
    ]
