# Generated by Django 5.2.1 on 2025-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange",
            "0004_rename_exchange_bu_action__4f7e2d_idx_exchange_bu_action__854ad6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="advisor_email",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="advisor_name",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="application_source",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="home_address",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="scholarship_status",
        ),
        migrations.AddField(
            model_name="exchange",
            name="academic_year",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exchange",
            name="current_semester",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exchange",
            name="degree",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="home_university",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="host_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exchange",
            name="host_university",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="major",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="program",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="referral_source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exchange",
            name="semester",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exchange",
            name="study_goals",
            field=models.TextField(blank=True),
        ),
    ]
