# Generated by Django 5.2.1 on 2025-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0005_remove_exchange_advisor_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(default=" ", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
