# Generated by Django 5.2.1 on 2025-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0006_userprofile_city_userprofile_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="street_address",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Prefer not to Say"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
