# Generated by Django 5.2.1 on 2025-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0007_rename_street_address_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
