# Generated by Django 5.2.1 on 2025-05-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0010_add_created_at_to_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchange",
            options={},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="academic_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="field_of_study",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="graduation_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interface_language",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="marketing_emails",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sms_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="timezone",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_program",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
