# Generated by Django 5.2.1 on 2025-05-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0011_alter_exchange_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchange",
            options={
                "permissions": [
                    ("can_review_exchange", "Can review exchange applications"),
                    (
                        "can_approve_exchange",
                        "Can approve/reject exchange applications",
                    ),
                    ("can_view_all_exchanges", "Can view all exchange applications"),
                ]
            },
        ),
    ]
