# Generated by Django 5.2.1 on 2025-05-29 21:30
# Generated by Django 5.2.1 on 2025-05-29 21:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_add_performance_indexes'),
    ]

    operations = [
    ]
