# Generated by Django 5.2.3 on 2025-10-15 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0003_alter_application_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the form', max_length=200)),
                ('form_type', models.CharField(choices=[('application', 'Exchange Application'), ('survey', 'Survey'), ('feedback', 'Feedback'), ('custom', 'Custom Form')], default='application', help_text='The purpose/type of this form', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the form')),
                ('schema', models.JSONField(blank=True, default=dict, help_text='JSON schema defining field structure')),
                ('ui_schema', models.JSONField(blank=True, default=dict, help_text='UI schema for form rendering (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_application_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Form Type',
                'verbose_name_plural': 'Application Form Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict, help_text='JSON object containing the form responses')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='Link to the exchange application this form is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='exchange.application')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='exchange.program')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='application_forms.formtype')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
