# Generated by Django 5.1.4 on 2026-04-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_forms", "0005_alter_formtype_created_by_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsteptemplate",
            name="default_step_key",
            field=models.CharField(
                help_text="Default step key (e.g. academics); must be unique on the target form when applied",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="required_document_type_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional DocumentType PKs attached to the generated step",
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="required_field_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Keys from schema_properties to add to the form-level required list",
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="schema_properties",
            field=models.JSONField(
                default=dict,
                help_text='JSON Schema property map merged into FormType.schema["properties"]',
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique id (auto-filled from name if left blank on save)",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="step_title",
            field=models.CharField(
                help_text="Default title for the step when applied to a form",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="formsteptemplate",
            name="ui_schema_fragment",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fragment merged into FormType.ui_schema",
            ),
        ),
        migrations.AlterField(
            model_name="formtype",
            name="step_definitions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Multi-step layout: list of {"key", "title", "field_names": [...], "required_document_type_ids": [optional DocumentType PKs], "visible_when": {optional same shape as x-seim-visibleWhen}}. IDs must exist and are enforced (with program required types) before advancing past that step. Empty = single-step form.',
            ),
        ),
    ]
