# Generated by Django 5.1.4 on 2026-04-08 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_usersettings_high_contrast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('operation_type', models.CharField(choices=[('USER_IMPORT', 'User Import'), ('USER_EXPORT', 'User Export'), ('USER_RESET_PASSWORDS', 'Reset User Passwords'), ('USER_DEACTIVATE', 'Deactivate Users'), ('PROGRAM_IMPORT', 'Program Import'), ('PROGRAM_EXPORT', 'Program Export'), ('APPLICATION_PROCESS', 'Process Applications'), ('DEMO_DATA_SETUP', 'Setup Demo Data'), ('DATABASE_RESET', 'Reset Database'), ('DATA_CLEANUP', 'Cleanup Data')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('max_records', models.IntegerField(default=0)),
                ('allowed_roles', models.JSONField(default=list)),
                ('custom_filters', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV'), ('EXCEL', 'Excel')], max_length=10)),
                ('include_fields', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV'), ('EXCEL', 'Excel')], max_length=10)),
                ('field_mapping', models.JSONField(default=dict)),
                ('validation_rules', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('DEMO_SETUP', 'Demo Setup'), ('DB_RESET', 'Database Reset'), ('CLEANUP', 'Cleanup')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('record_count', models.IntegerField(default=0)),
                ('operation_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoDataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_data_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=10)),
                ('custom_filters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_permissions', to='accounts.role')),
            ],
            options={
                'ordering': ['role__name', 'model_name'],
                'unique_together': {('role', 'model_name', 'permission_type')},
            },
        ),
    ]
