# Generated by Django 5.1.4 on 2025-11-20 15:15

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0006_savedsearch'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('published_date', models.DateField(verbose_name='Post date')),
                ('introduction', models.TextField(help_text='Post summary/excerpt', max_length=500)),
                ('body', wagtail.fields.StreamField([('rich_text', 1), ('image', 5), ('call_to_action', 12), ('card_grid', 21), ('testimonial', 23), ('faq', 29), ('hero', 31), ('video', 33), ('document', 35), ('process_steps', 41), ('two_columns', 47), ('embedded_form', 50)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'help_text': 'Rich text content with formatting options'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('light', 'Light'), ('dark', 'Dark')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('button_text', 8), ('button_link', 9), ('button_page', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-globe')", 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('icon', 15), ('title', 6), ('text', 16), ('link', 9), ('link_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('cards', 19), ('columns', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 6), ('author_title', 13), ('author_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'max_length': 100, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 24), ('items', 28)]], {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('dark', 'Dark')]}), 31: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 14), ('background_image', 22), ('background_color', 30), ('button_text', 17), ('button_link', 9), ('button_page', 10)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or other supported video URL', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video', 32), ('caption', 3)]], {}), 34: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('document', 34), ('title', 13), ('description', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': True}), 37: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-check-circle')", 'max_length': 50, 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('number', 36), ('title', 6), ('description', 37), ('icon', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('steps', 40)]], {}), 42: ('wagtail.blocks.RichTextBlock', (), {}), 43: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 44: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 45: ('wagtail.blocks.StreamBlock', [[('rich_text', 42), ('image', 43), ('document', 44)]], {'use_json_field': True}), 46: ('wagtail.blocks.StructBlock', [[('content', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('left_column', 46), ('right_column', 46)]], {}), 48: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a form page to embed', 'page_type': ['cms.FormPage'], 'required': True}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('form_page', 48), ('show_title', 49)]], {})}, help_text='Post content')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='posts', to='cms.blogcategory')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-first_published_at'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='FAQIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'FAQ Index Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('rich_text', 1), ('image', 5), ('call_to_action', 12), ('card_grid', 21), ('testimonial', 23), ('faq', 29), ('hero', 31), ('video', 33), ('document', 35), ('process_steps', 41), ('two_columns', 47), ('embedded_form', 50)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'help_text': 'Rich text content with formatting options'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('light', 'Light'), ('dark', 'Dark')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('button_text', 8), ('button_link', 9), ('button_page', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-globe')", 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('icon', 15), ('title', 6), ('text', 16), ('link', 9), ('link_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('cards', 19), ('columns', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 6), ('author_title', 13), ('author_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'max_length': 100, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 24), ('items', 28)]], {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('dark', 'Dark')]}), 31: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 14), ('background_image', 22), ('background_color', 30), ('button_text', 17), ('button_link', 9), ('button_page', 10)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or other supported video URL', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video', 32), ('caption', 3)]], {}), 34: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('document', 34), ('title', 13), ('description', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': True}), 37: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-check-circle')", 'max_length': 50, 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('number', 36), ('title', 6), ('description', 37), ('icon', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('steps', 40)]], {}), 42: ('wagtail.blocks.RichTextBlock', (), {}), 43: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 44: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 45: ('wagtail.blocks.StreamBlock', [[('rich_text', 42), ('image', 43), ('document', 44)]], {'use_json_field': True}), 46: ('wagtail.blocks.StructBlock', [[('content', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('left_column', 46), ('right_column', 46)]], {}), 48: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a form page to embed', 'page_type': ['cms.FormPage'], 'required': True}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('form_page', 48), ('show_title', 49)]], {})}, help_text='FAQ content (use FAQ blocks for Q&A sections)')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'FAQ Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission')),
                ('linked_program', models.ForeignKey(blank=True, help_text='Link this form to an exchange program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_pages', to='exchange.program')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Form Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='cms.formpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('hero_title', models.CharField(default='Student Exchange Information Manager', max_length=200)),
                ('hero_subtitle', models.TextField(default='Streamline your student exchange program management', max_length=500)),
                ('hero_cta_text', models.CharField(blank=True, default='Get Started', max_length=50)),
                ('body', wagtail.fields.StreamField([('rich_text', 1), ('image', 5), ('call_to_action', 12), ('card_grid', 21), ('testimonial', 23), ('faq', 29), ('hero', 31), ('video', 33), ('document', 35), ('process_steps', 41), ('two_columns', 47), ('embedded_form', 50)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'help_text': 'Rich text content with formatting options'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('light', 'Light'), ('dark', 'Dark')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('button_text', 8), ('button_link', 9), ('button_page', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-globe')", 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('icon', 15), ('title', 6), ('text', 16), ('link', 9), ('link_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('cards', 19), ('columns', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 6), ('author_title', 13), ('author_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'max_length': 100, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 24), ('items', 28)]], {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('dark', 'Dark')]}), 31: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 14), ('background_image', 22), ('background_color', 30), ('button_text', 17), ('button_link', 9), ('button_page', 10)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or other supported video URL', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video', 32), ('caption', 3)]], {}), 34: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('document', 34), ('title', 13), ('description', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': True}), 37: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-check-circle')", 'max_length': 50, 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('number', 36), ('title', 6), ('description', 37), ('icon', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('steps', 40)]], {}), 42: ('wagtail.blocks.RichTextBlock', (), {}), 43: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 44: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 45: ('wagtail.blocks.StreamBlock', [[('rich_text', 42), ('image', 43), ('document', 44)]], {'use_json_field': True}), 46: ('wagtail.blocks.StructBlock', [[('content', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('left_column', 46), ('right_column', 46)]], {}), 48: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a form page to embed', 'page_type': ['cms.FormPage'], 'required': True}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('form_page', 48), ('show_title', 49)]], {})}, help_text='Main content area with flexible blocks', null=True)),
                ('hero_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProgramIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Program Index Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', models.TextField(help_text='Program summary', max_length=500)),
                ('body', wagtail.fields.StreamField([('rich_text', 1), ('image', 5), ('call_to_action', 12), ('card_grid', 21), ('testimonial', 23), ('faq', 29), ('hero', 31), ('video', 33), ('document', 35), ('process_steps', 41), ('two_columns', 47), ('embedded_form', 50)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'help_text': 'Rich text content with formatting options'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('light', 'Light'), ('dark', 'Dark')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('button_text', 8), ('button_link', 9), ('button_page', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-globe')", 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('icon', 15), ('title', 6), ('text', 16), ('link', 9), ('link_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('cards', 19), ('columns', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 6), ('author_title', 13), ('author_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'max_length': 100, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 24), ('items', 28)]], {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('dark', 'Dark')]}), 31: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 14), ('background_image', 22), ('background_color', 30), ('button_text', 17), ('button_link', 9), ('button_page', 10)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or other supported video URL', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video', 32), ('caption', 3)]], {}), 34: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('document', 34), ('title', 13), ('description', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': True}), 37: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-check-circle')", 'max_length': 50, 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('number', 36), ('title', 6), ('description', 37), ('icon', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('steps', 40)]], {}), 42: ('wagtail.blocks.RichTextBlock', (), {}), 43: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 44: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 45: ('wagtail.blocks.StreamBlock', [[('rich_text', 42), ('image', 43), ('document', 44)]], {'use_json_field': True}), 46: ('wagtail.blocks.StructBlock', [[('content', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('left_column', 46), ('right_column', 46)]], {}), 48: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a form page to embed', 'page_type': ['cms.FormPage'], 'required': True}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('form_page', 48), ('show_title', 49)]], {})}, help_text='Detailed program information')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
                ('program', models.OneToOneField(blank=True, help_text='Link to the exchange program in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_page', to='exchange.program')),
            ],
            options={
                'verbose_name': 'Program Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('introduction', models.TextField(blank=True, help_text='Page introduction/summary', max_length=500)),
                ('body', wagtail.fields.StreamField([('rich_text', 1), ('image', 5), ('call_to_action', 12), ('card_grid', 21), ('testimonial', 23), ('faq', 29), ('hero', 31), ('video', 33), ('document', 35), ('process_steps', 41), ('two_columns', 47), ('embedded_form', 50)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'help_text': 'Rich text content with formatting options'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)'), ('light', 'Light'), ('dark', 'Dark')]}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('button_text', 8), ('button_link', 9), ('button_page', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-globe')", 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('icon', 15), ('title', 6), ('text', 16), ('link', 9), ('link_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')]}), 21: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('cards', 19), ('columns', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('quote', 16), ('author', 6), ('author_title', 13), ('author_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'max_length': 100, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 24), ('items', 28)]], {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('info', 'Info (Cyan)'), ('dark', 'Dark')]}), 31: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 14), ('background_image', 22), ('background_color', 30), ('button_text', 17), ('button_link', 9), ('button_page', 10)]], {}), 32: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube, Vimeo, or other supported video URL', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('video', 32), ('caption', 3)]], {}), 34: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StructBlock', [[('document', 34), ('title', 13), ('description', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'max_length': 10, 'required': True}), 37: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': "Bootstrap icon class (e.g., 'bi-check-circle')", 'max_length': 50, 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('number', 36), ('title', 6), ('description', 37), ('icon', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 14), ('steps', 40)]], {}), 42: ('wagtail.blocks.RichTextBlock', (), {}), 43: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 44: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 45: ('wagtail.blocks.StreamBlock', [[('rich_text', 42), ('image', 43), ('document', 44)]], {'use_json_field': True}), 46: ('wagtail.blocks.StructBlock', [[('content', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('left_column', 46), ('right_column', 46)]], {}), 48: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a form page to embed', 'page_type': ['cms.FormPage'], 'required': True}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 50: ('wagtail.blocks.StructBlock', [[('form_page', 48), ('show_title', 49)]], {})}, help_text='Main content area with flexible blocks')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('sidebar_content', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
                ('related_pages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Standard Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
