# Generated by Django 5.1.4 on 2026-04-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cgripage_convenioindexpage_conveniopage_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Optional image in the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle below the title', max_length=200),
        ),
    ]
