# Generated by Django 5.1.4 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_standardpage_subtitle_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conveniopage",
            name="agreement_type",
            field=models.CharField(
                choices=[
                    ("bilateral", "Bilateral"),
                    ("multilateral", "Multilateral"),
                    ("erasmus", "Erasmus+"),
                    ("conahec", "CONAHEC"),
                    ("specific", "Specific Program"),
                ],
                default="bilateral",
                max_length=50,
            ),
        ),
    ]
