# Generated by Django 5.2.17

from django.db import migrations, models


def default_faq_audiences():
    return ["student"]


def default_faq_surfaces():
    return ["public", "spa"]


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_blogpostpage_body_alter_cgripage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqindexpage",
            name="index_kind",
            field=models.CharField(
                choices=[
                    ("public", "Public FAQ index"),
                    ("spa_help", "SPA help index (not public)"),
                ],
                default="public",
                help_text="Public indexes appear on the marketing site. SPA help indexes 404 publicly.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="audiences",
            field=models.JSONField(
                blank=True,
                default=default_faq_audiences,
                help_text="Who may see this article in the SPA help hub.",
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="contextual_keys",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated Vue route names (e.g. ApplicationNew,ApplicationEdit).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="surfaces",
            field=models.JSONField(
                blank=True,
                default=default_faq_surfaces,
                help_text="Where this article is published (public site and/or SPA).",
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("getting_started", "Getting started"),
                    ("applications", "Applications"),
                    ("documents", "Documents"),
                    ("review", "Review"),
                    ("partner", "Partner"),
                    ("admin", "Admin"),
                    ("account", "Account"),
                ],
                default="",
                help_text="Grouping key for the SPA help hub.",
                max_length=32,
            ),
        ),
    ]
