# Generated by Django 5.2.3 on 2025-10-15 15:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name of the grading scale (e.g., 'US GPA 4.0 Scale')", max_length=255)),
                ('code', models.CharField(help_text="Unique code for the scale (e.g., 'US_GPA_4', 'ECTS')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the grading scale')),
                ('country', models.CharField(blank=True, help_text='Country or region where this scale is used', max_length=100)),
                ('min_value', models.FloatField(help_text='Minimum possible grade value in this scale')),
                ('max_value', models.FloatField(help_text='Maximum possible grade value in this scale')),
                ('passing_value', models.FloatField(help_text='Minimum grade value required to pass')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scale is currently in use')),
                ('is_reverse_scale', models.BooleanField(default=False, help_text='True if lower values are better (e.g., German scale 1.0-5.0)')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['country', 'name'],
                'indexes': [models.Index(fields=['code'], name='grade_scale_code_idx'), models.Index(fields=['is_active'], name='grade_scale_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Grade label (e.g., 'A', '1.0', 'First Class')", max_length=50)),
                ('numeric_value', models.FloatField(help_text='Numeric representation within the scale')),
                ('gpa_equivalent', models.FloatField(help_text='Normalized 4.0 GPA equivalent for cross-scale comparison', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('min_percentage', models.FloatField(blank=True, help_text='Minimum percentage for this grade (optional)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_percentage', models.FloatField(blank=True, help_text='Maximum percentage for this grade (optional)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('description', models.TextField(blank=True, help_text='Description of what this grade represents')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the scale')),
                ('is_passing', models.BooleanField(default=True, help_text='Whether this grade is considered passing')),
                ('grade_scale', models.ForeignKey(help_text='The grade scale this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_values', to='grades.gradescale')),
            ],
            options={
                'verbose_name': 'Grade Value',
                'verbose_name_plural': 'Grade Values',
                'ordering': ['grade_scale', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GradeTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence level of this translation (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True, help_text='Translation notes or rationale')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this translation mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_grade', models.ForeignKey(help_text='Source grade value', on_delete=django.db.models.deletion.CASCADE, related_name='translations_from', to='grades.gradevalue')),
                ('target_grade', models.ForeignKey(help_text='Target grade value', on_delete=django.db.models.deletion.CASCADE, related_name='translations_to', to='grades.gradevalue')),
            ],
            options={
                'verbose_name': 'Grade Translation',
                'verbose_name_plural': 'Grade Translations',
            },
        ),
        migrations.AddIndex(
            model_name='gradevalue',
            index=models.Index(fields=['grade_scale', 'gpa_equivalent'], name='grade_val_gpa_idx'),
        ),
        migrations.AddIndex(
            model_name='gradevalue',
            index=models.Index(fields=['grade_scale', 'numeric_value'], name='grade_val_num_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradevalue',
            unique_together={('grade_scale', 'label'), ('grade_scale', 'numeric_value')},
        ),
        migrations.AddIndex(
            model_name='gradetranslation',
            index=models.Index(fields=['source_grade'], name='grade_trans_src_idx'),
        ),
        migrations.AddIndex(
            model_name='gradetranslation',
            index=models.Index(fields=['target_grade'], name='grade_trans_tgt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradetranslation',
            unique_together={('source_grade', 'target_grade')},
        ),
    ]
