# Generated by Django 5.2.3 on 2025-07-11 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0004_formtype_wizard'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_form',
            field=models.ForeignKey(blank=True, help_text='Dynamic application form for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynforms.formtype'),
        ),
    ]
