# Generated by Django 5.2.3 on 2025-10-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0001_initial'),
        ('exchange', '0003_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='application_form',
            field=models.ForeignKey(blank=True, help_text='Dynamic application form for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_forms.formtype'),
        ),
    ]
