# Generated by Django 5.2.3 on 2025-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_program_application_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='program',
            name='auto_reject_ineligible',
            field=models.BooleanField(default=False, help_text="Automatically reject applications that don't meet eligibility criteria."),
        ),
        migrations.AddField(
            model_name='program',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age for eligibility.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age for eligibility.', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_language_level',
            field=models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], help_text='Minimum language proficiency level (CEFR scale).', max_length=10, null=True),
        ),
    ]
