# Generated by Django 5.2.3 on 2025-11-11 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_program_options_program_auto_reject_ineligible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name for this saved search', max_length=100)),
                ('search_type', models.CharField(choices=[('program', 'Program Search'), ('application', 'Application Search')], help_text='Type of search (programs or applications)', max_length=20)),
                ('filters', models.JSONField(default=dict, help_text='JSON object containing filter parameters')),
                ('is_default', models.BooleanField(default=False, help_text='Use this search as default for this user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'search_type'], name='savedsearch_user_type_idx'), models.Index(fields=['user', 'is_default'], name='savedsearch_user_default_idx')],
            },
        ),
    ]
