# Generated by Django 5.1.4 on 2026-04-17 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0016_alter_savedsearch_search_type_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="timelineevent",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="exchange.application",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="exchange.application",
            ),
        ),
    ]
