# Generated by Django 5.1.4 on 2026-04-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0017_alter_comment_options_alter_timelineevent_options_and_more"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="workflow_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Published workflow version governing application behavior for this program.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="workflows.workflowversion",
            ),
        ),
    ]
