# Generated by Django 5.1.4 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0018_program_workflow_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityRuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("rules_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="eligibility_ruleset",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional: persisted eligibility rule set used for previews/validation when enabled. "
                    "When unset, eligibility rules are derived from program fields."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="exchange.eligibilityruleset",
            ),
        ),
    ]

