# Generated by Django 5.1.4 on 2026-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_eligibility_ruleset_and_program_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeagreement',
            name='partner_reference_id',
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='application_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of applications permitted under this agreement.', null=True),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='custom_tags',
            field=models.CharField(blank=True, help_text="Custom tags restricted to 'Foreign Language' or 'Habla Hispana'.", max_length=50),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='language_requirements',
            field=models.JSONField(blank=True, default=list, help_text="List of required languages and levels, e.g., [{'lang': 'French', 'level': 'B2'}]"),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='notify_on_limit_reached',
            field=models.BooleanField(default=True, help_text='If true, an alert is sent when the application limit is reached.'),
        ),
        migrations.AddField(
            model_name='exchangeagreement',
            name='required_gpa',
            field=models.FloatField(blank=True, help_text='Minimum GPA required for the agreement.', null=True),
        ),
    ]
