# Generated by Django 5.1.15 on 2026-08-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0020_remove_exchangeagreement_partner_reference_id_and_more"),
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_languages_at_apply",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="credits_percent_at_apply",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gpa_at_apply",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="grade_scale_at_apply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_at_apply",
                to="grades.gradescale",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="language_at_apply",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="language_level_at_apply",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="semester_at_apply",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="min_credits_approved_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum percentage of approved credits required (0–100).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_semester",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum academic semester required for eligibility.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="min_gpa",
            field=models.FloatField(
                blank=True,
                help_text="Minimum GPA required for eligibility (4.0-normalized via student grade scale).",
                null=True,
            ),
        ),
    ]
