# Generated by Django 5.1.15 on 2026-08-13 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0022_seed_mobility_schemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostInstitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Mobility scheme this host university belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_institutions",
                        to="exchange.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host institution",
                "verbose_name_plural": "Host institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostSchool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="exchange.hostinstitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host school",
                "verbose_name_plural": "Host schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostAcademicProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_programs",
                        to="exchange.hostschool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host academic program",
                "verbose_name_plural": "Host academic programs",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="host_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected host university for this application.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="exchange.hostinstitution",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="host_school",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected host school / faculty.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="exchange.hostschool",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="host_academic_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected host academic program.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="exchange.hostacademicprogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostinstitution",
            constraint=models.UniqueConstraint(
                fields=("program", "name"), name="uniq_host_institution_program_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostschool",
            constraint=models.UniqueConstraint(
                fields=("institution", "name"), name="uniq_host_school_institution_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostacademicprogram",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uniq_host_academic_program_school_name"
            ),
        ),
    ]
