# Generated by Django 5.1.15 on 2026-08-13 18:38 — edited to preserve M2M links + seed catalog

import django.db.models.deletion
from django.db import migrations, models


def copy_required_document_m2m(apps, schema_editor):
    """Preserve existing Program ↔ DocumentType links into ProgramDocumentRequirement."""
    ProgramDocumentRequirement = apps.get_model(
        "exchange", "ProgramDocumentRequirement"
    )
    connection = schema_editor.connection
    table = "exchange_program_required_document_types"
    with connection.cursor() as cursor:
        existing = connection.introspection.table_names()
        if table not in existing:
            return
        cursor.execute(f"SELECT program_id, documenttype_id FROM {table}")
        rows = cursor.fetchall()
    for index, (program_id, documenttype_id) in enumerate(rows):
        ProgramDocumentRequirement.objects.get_or_create(
            program_id=program_id,
            document_type_id=documenttype_id,
            defaults={"is_required": True, "sort_order": index * 10},
        )


def seed_mobility_document_catalog(apps, schema_editor):
    """Seed Mexican mobility DocumentTypes and scheme requirements."""
    from documents.mobility_document_catalog import (
        assign_scheme_document_requirements,
        seed_mobility_document_types,
    )

    seed_mobility_document_types()
    assign_scheme_document_requirements(
        program_model=apps.get_model("exchange", "Program"),
        requirement_model=apps.get_model(
            "exchange", "ProgramDocumentRequirement"
        ),
        document_type_model=apps.get_model("documents", "DocumentType"),
    )


def drop_legacy_m2m_table(apps, schema_editor):
    connection = schema_editor.connection
    table = "exchange_program_required_document_types"
    with connection.cursor() as cursor:
        if table in connection.introspection.table_names():
            cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documenttype_catalog_phase4"),
        ("exchange", "0023_host_destination_hierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="When false, shown on checklist but not required for submit.",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Absolute upload deadline for this document type.",
                        null=True,
                    ),
                ),
                (
                    "deadline_days_before_program_deadline",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Relative deadline: N days before the program application_deadline.",
                        null=True,
                    ),
                ),
                (
                    "instructions_override",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional per-program override of DocumentType.instructions.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_requirements",
                        to="documents.documenttype",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_document_requirements",
                        to="exchange.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program document requirement",
                "verbose_name_plural": "Program document requirements",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(copy_required_document_m2m, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="program",
                    name="required_document_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "Applicants must upload these document types and have them "
                            "marked valid before submitting."
                        ),
                        related_name="programs_requiring",
                        through="exchange.ProgramDocumentRequirement",
                        to="documents.documenttype",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_legacy_m2m_table, migrations.RunPython.noop),
            ],
        ),
        migrations.AddConstraint(
            model_name="programdocumentrequirement",
            constraint=models.UniqueConstraint(
                fields=("program", "document_type"),
                name="uniq_program_document_requirement",
            ),
        ),
        migrations.RunPython(
            seed_mobility_document_catalog, migrations.RunPython.noop
        ),
    ]
