# Generated by Django 5.1.15 on 2026-08-13 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0024_program_document_requirement_phase4"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credit value at the host institution (optional).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exchange.hostacademicprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host subject",
                "verbose_name_plural": "Host subjects",
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationSubjectSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "home_course_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label of the corresponding home institution course.",
                        max_length=255,
                    ),
                ),
                (
                    "home_course_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional code of the corresponding home institution course.",
                        max_length=64,
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credits used for homologación (defaults to host subject credits).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_selections",
                        to="exchange.application",
                    ),
                ),
                (
                    "host_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_selections",
                        to="exchange.hostsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application subject selection",
                "verbose_name_plural": "Application subject selections",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="hostsubject",
            constraint=models.UniqueConstraint(
                fields=("academic_program", "name", "code"),
                name="uniq_host_subject_program_name_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationsubjectselection",
            constraint=models.UniqueConstraint(
                fields=("application", "host_subject"),
                name="uniq_application_host_subject_selection",
            ),
        ),
    ]
