# Generated by Django 5.2.3 on 2025-07-10 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address', null=True)),
                ('device', models.CharField(blank=True, help_text='Device identifier', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Location information', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text="User's preferred theme", max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text="User's preferred font size", max_length=20)),
                ('email_applications', models.BooleanField(default=True, help_text='Email notifications for application updates')),
                ('email_documents', models.BooleanField(default=True, help_text='Email notifications for document uploads')),
                ('email_programs', models.BooleanField(default=False, help_text='Email notifications for new programs')),
                ('email_system', models.BooleanField(default=True, help_text='Email notifications for system messages')),
                ('inapp_applications', models.BooleanField(default=True, help_text='In-app notifications for application updates')),
                ('inapp_documents', models.BooleanField(default=True, help_text='In-app notifications for document uploads')),
                ('inapp_comments', models.BooleanField(default=True, help_text='In-app notifications for comments')),
                ('profile_public', models.BooleanField(default=False, help_text='Make profile visible to other users')),
                ('share_analytics', models.BooleanField(default=True, help_text='Share usage analytics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
