# Generated by Django 5.2.3 on 2025-10-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession_usersettings'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade_scale',
            field=models.ForeignKey(blank=True, help_text="The grading scale used by the student's institution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='grades.gradescale'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(blank=True, help_text="Student's GPA/grade in their institutional grading scale", null=True),
        ),
    ]
