# Generated by Django 5.2.3 on 2025-10-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_grade_scale_alter_profile_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Student's date of birth for age verification", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level',
            field=models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], help_text='Language proficiency level (CEFR scale)', max_length=10, null=True),
        ),
    ]
