# Generated by Django 5.2.3 on 2025-11-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permission_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Enable high contrast mode for improved visibility'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reduce_motion',
            field=models.BooleanField(default=False, help_text='Reduce animations and transitions for accessibility'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('x-large', 'Extra Large')], default='normal', help_text="User's preferred font size", max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', help_text="User's preferred theme", max_length=20),
        ),
    ]
