# Generated by Django 5.1.4 on 2026-04-17 01:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usersettings_inapp_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="additional_languages",
            field=models.JSONField(
                blank=True,
                default=accounts.models._default_additional_languages,
                help_text='Other languages and CEFR levels, e.g. [{"name": "German", "level": "B2"}].',
            ),
        ),
    ]
