# Generated by Django 5.1.15 on 2026-08-13 18:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_seed_student_profile_catalogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="credits_approved_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of program credits approved (0–100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="current_semester",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional override for current semester; when unset, derived from ingress_date.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ingress_date",
            field=models.DateField(
                blank=True,
                help_text="Date the student entered their current academic program (used to estimate semester).",
                null=True,
            ),
        ),
    ]
