# Generated by Django 5.2.17 on 2026-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_drop_unused_plugins_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarconnection',
            name='event_map',
            field=models.JSONField(blank=True, default=dict, help_text='Map of SEIM event id → Google Calendar event id.'),
        ),
    ]
