# Generated by Django 5.2.1 on 2025-05-31 11:52

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='The answer provided by the applicant (for text, yes/no, or open-ended questions).', null=True)),
                ('selected_option_id', models.IntegerField(blank=True, help_text="ID of the selected option if the question type is 'select'.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the status.', max_length=100)),
                ('color_code', models.CharField(default='#000000', help_text='Hex color code for UI tags.', max_length=7)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_for_stage', models.CharField(choices=[('APPLICATION', 'Application'), ('REVIEW', 'Review'), ('ACCEPTANCE', 'Acceptance'), ('FINALIZATION', 'Finalization')], max_length=20)),
                ('upload_instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('iso_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiencyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('min_score', models.CharField()),
                ('max_score', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProficiencyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('scale_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('ALPHABETIC', 'Alphabetic'), ('ALPHANUMERIC', 'Alphanumeric')])),
                ('min_level', models.CharField()),
                ('max_level', models.CharField()),
                ('has_plus', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('min_duration', models.PositiveIntegerField(help_text='Minimum duration')),
                ('max_duration', models.PositiveIntegerField(help_text='Maximum duration')),
                ('duration_unit', models.CharField(choices=[('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('SEMESTERS', 'Semesters'), ('YEARS', 'Years')], max_length=20)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum GPA required', max_digits=4, null=True)),
                ('language_requirements', models.JSONField(default=dict, help_text="Language requirements (e.g., {'english': 'TOEFL 90+', 'german': 'B2'})")),
                ('eligible_degrees', models.JSONField(default=list, help_text='List of eligible degree programs')),
                ('eligible_years', models.JSONField(default=list, help_text='List of eligible academic years (e.g., [2, 3, 4])')),
                ('student_semesters_remaining_after_exchange', models.JSONField(default=list, help_text='Minimum semesters a student must have after the exchange in their host university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('text', 'Text'), ('select', 'Select')], max_length=10)),
                ('select_model', models.CharField(blank=True, help_text="Specify model for select (e.g., 'app_label.ModelName').", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='State/province code', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['-submission_date', '-created_at'], 'permissions': [('can_review_exchange', 'Can review exchange applications'), ('can_approve_exchange', 'Can approve/reject exchange applications'), ('can_view_all_exchanges', 'Can view all exchange applications'), ('can_cancel_exchange', 'Can cancel exchange applications')]},
        ),
        migrations.AlterModelOptions(
            name='exchangeprogram',
            options={'ordering': ['priority_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='exchangeprogram',
            name='exchange_program_code_idx',
        ),
        migrations.RemoveField(
            model_name='contactprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='destination_university',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='home_university',
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='duration_options',
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='funding_details',
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='has_funding',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_program',
        ),
        migrations.RemoveField(
            model_name='university',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='university',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_profiles', to='exchange.university'),
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='tt', help_text='ISO 3166-1 alpha-3 country code', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='country',
            name='label',
            field=models.CharField(default='tt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text='International dialing code', max_length=5),
        ),
        migrations.AddField(
            model_name='exchange',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchange',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchange',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exchange',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exchange',
            name='language_proficiencies',
            field=models.JSONField(blank=True, default=dict, help_text='Language proficiency scores/certificates'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='application_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='application_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='countries',
            field=models.JSONField(default=list, help_text='List of countries covered by this program'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly funding amount if available', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='funding_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants per period', null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='partner_universities',
            field=models.JSONField(default=list, help_text='List of partner universities and their details'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='priority_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order priority (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='program_type',
            field=models.CharField(choices=[('BILATERAL', 'Bilateral Agreement'), ('ERASMUS', 'Erasmus+'), ('GLOBAL', 'Global Exchange'), ('SUMMER', 'Summer Program'), ('RESEARCH', 'Research Exchange'), ('INTERNSHIP', 'Internship Program')], default='tt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='required_documents',
            field=models.JSONField(default=list, help_text='List of required document types for this program'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partneragreement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partneragreement',
            name='label',
            field=models.CharField(default='tt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partneragreement',
            name='name',
            field=models.CharField(default='tt', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='exchange.university'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', 'Prefer not to say')], max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='exchange.university'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='label',
            field=models.CharField(default='tt', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the course (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('APPROVED', 'Approved in Learning Agreement'), ('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('REPLACED', 'Replaced')], default='PLANNED', help_text='Status of the course in the exchange process.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='current_university',
            field=models.CharField(blank=True, help_text="Student's current university", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='destination_country',
            field=models.CharField(blank=True, help_text='Country of the host university', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='end_date',
            field=models.DateField(blank=True, help_text='Exchange end date', null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_program',
            field=models.ForeignKey(blank=True, help_text='Selected exchange program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.exchangeprogram'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current GPA', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='host_university',
            field=models.CharField(blank=True, help_text='Destination university for exchange', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='motivation_letter',
            field=models.TextField(blank=True, help_text="Student's motivation for the exchange", null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How the student learned about the program', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or accommodations needed', null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='start_date',
            field=models.DateField(blank=True, help_text='Exchange start date', null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the application', max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='student',
            field=models.ForeignKey(help_text='Student applying for the exchange', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='study_goals',
            field=models.TextField(blank=True, help_text='Academic goals for the exchange', null=True),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='code',
            field=models.CharField(help_text='Program identification code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['exchange_program', 'status'], name='exchange_program_status_idx'),
        ),
        migrations.AddField(
            model_name='applicationanswer',
            name='exchange',
            field=models.ForeignKey(help_text='The related Exchange application instance.', on_delete=django.db.models.deletion.CASCADE, related_name='application_answers', to='exchange.exchange'),
        ),
        migrations.AddField(
            model_name='campus',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.country'),
        ),
        migrations.AddField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='exchange.university'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.country'),
        ),
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.city'),
        ),
        migrations.AddField(
            model_name='degree',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.campus'),
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.university'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='funding_types',
            field=models.ManyToManyField(blank=True, help_text='Available funding types for this program', related_name='exchange_programs', to='exchange.fundingtype'),
        ),
        migrations.AddField(
            model_name='institution',
            name='main_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.contactprofile'),
        ),
        migrations.AddField(
            model_name='degree',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.institution'),
        ),
        migrations.AddField(
            model_name='languageproficiencytest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.language'),
        ),
        migrations.AddField(
            model_name='languageproficiencytest',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.proficiencylevels'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='program_requirements',
            field=models.ForeignKey(blank=True, help_text='Requirements for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.programrequirements'),
        ),
        migrations.AddIndex(
            model_name='exchangeprogram',
            index=models.Index(fields=['is_active', 'program_type'], name='exchange_ex_is_acti_8a04d5_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeprogram',
            index=models.Index(fields=['application_start_date', 'application_end_date'], name='exchange_ex_applica_3bb165_idx'),
        ),
        migrations.AddField(
            model_name='applicationanswer',
            name='question',
            field=models.ForeignKey(help_text='The question being answered. Restricted deletion to preserve answer integrity.', on_delete=django.db.models.deletion.RESTRICT, related_name='application_answers', to='exchange.question'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', to='exchange.question'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='exchange.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='exchange.state'),
        ),
        migrations.AddField(
            model_name='campus',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.state'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'code')},
        ),
    ]
