# Generated by Django 5.2.3 on 2025-10-15 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('exchange', '0003_alter_application_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application', 'type'], name='doc_app_type_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='doc_uploaded_by_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_valid'], name='doc_is_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['validated_at'], name='doc_validated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='doc_created_desc_idx'),
        ),
    ]
