# Generated by Django 5.1.15 on 2026-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_exchangeagreementdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="documenttype",
            name="accepted_extensions",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated extensions without dots (e.g. pdf,jpg,png). Empty = global defaults.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="allows_multiple",
            field=models.BooleanField(
                default=False,
                help_text="Allow more than one upload of this type per application.",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="faq",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional FAQ / tips shown alongside instructions.",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Student-facing instructions / FAQ body.",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="max_file_size_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per-type size cap in MB. Empty = global default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable key (e.g. solicitud_participacion).",
                max_length=80,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="submission_mode",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("template_download", "Template download"),
                    ("system_generated", "System generated"),
                    ("instructions_only", "Instructions only"),
                ],
                db_index=True,
                default="upload",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="template_file",
            field=models.FileField(
                blank=True,
                help_text="Downloadable blank template for students.",
                null=True,
                upload_to="document_templates/",
            ),
        ),
    ]
