# Create/configure a named Cloudflare Tunnel with a stable DNS hostname.
#
# Prerequisites:
#   1. cloudflared login completed (cert at %USERPROFILE%\.cloudflared\cert.pem)
#   2. Domain DNS already managed by Cloudflare
#
# Usage:
#   .\scripts\setup-named-cloudflare-tunnel.ps1 -Hostname seim.example.com
#   .\scripts\setup-named-cloudflare-tunnel.ps1 -Hostname seim.example.com -TunnelName seim-localprod
param(
    [Parameter(Mandatory = $true)]
    [string]$Hostname,

    [string]$TunnelName = "seim-localprod",
    [string]$BackendUrl = "http://127.0.0.1:8020"
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Cloudflared = Join-Path $ProjectRoot "tools\cloudflared\cloudflared.exe"
$ConfigDir = Join-Path $ProjectRoot "config\cloudflared"
$ConfigFile = Join-Path $ConfigDir "config.yml"
$UrlFile = Join-Path $ProjectRoot "logs\cloudflare-tunnel.url"
$Cert = Join-Path $env:USERPROFILE ".cloudflared\cert.pem"

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

if (-not (Test-Path $Cloudflared)) {
    throw "Missing $Cloudflared"
}
if (-not (Test-Path $Cert)) {
    throw @"
Missing Cloudflare origin cert at $Cert

Run:
  & '$Cloudflared' tunnel login

Authorize in the browser and select the zone that will host '$Hostname'.
"@
}

$Hostname = $Hostname.Trim().ToLowerInvariant() -replace '^https?://', '' -replace '/$', ''
if ($Hostname -notmatch '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$') {
    throw "Invalid hostname: $Hostname"
}

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $ProjectRoot "logs") | Out-Null

Write-Step "Listing existing tunnels"
$existingJson = & $Cloudflared tunnel list --output json 2>$null
$tunnelId = $null
if ($existingJson) {
    $tunnels = $existingJson | ConvertFrom-Json
    $match = @($tunnels) | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
    if ($match) {
        $tunnelId = $match.id
        Write-Step "Reusing tunnel '$TunnelName' ($tunnelId)"
    }
}

if (-not $tunnelId) {
    Write-Step "Creating tunnel '$TunnelName'"
    & $Cloudflared tunnel create $TunnelName
    if ($LASTEXITCODE -ne 0) { throw "tunnel create failed" }
    $existingJson = & $Cloudflared tunnel list --output json
    $tunnels = $existingJson | ConvertFrom-Json
    $match = @($tunnels) | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
    if (-not $match) { throw "Tunnel created but not found in list" }
    $tunnelId = $match.id
    Write-Step "Created tunnel id $tunnelId"
}

$credCandidates = @(
    (Join-Path $env:USERPROFILE ".cloudflared\$tunnelId.json"),
    (Join-Path $ConfigDir "$tunnelId.json")
)
$credFile = $credCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $credFile) {
    # Newer cloudflared may place credentials under ~/.cloudflared only
    $credFile = Join-Path $env:USERPROFILE ".cloudflared\$tunnelId.json"
    if (-not (Test-Path $credFile)) {
        throw "Credentials file not found for tunnel $tunnelId (expected $credFile)"
    }
}

# Copy credentials into project config for service-friendly absolute paths.
$projectCred = Join-Path $ConfigDir "$tunnelId.json"
if ($credFile -ne $projectCred) {
    Copy-Item $credFile $projectCred -Force
    $credFile = $projectCred
}

Write-Step "Writing $ConfigFile"
@"
# Generated by setup-named-cloudflare-tunnel.ps1 — do not commit secrets.
tunnel: $tunnelId
credentials-file: $(($credFile -replace '\\', '/'))
protocol: http2

ingress:
  - hostname: $Hostname
    service: $BackendUrl
    originRequest:
      connectTimeout: 30s
  - service: http_status:404
"@ | Set-Content -Path $ConfigFile -Encoding utf8

Write-Step "Routing DNS $Hostname -> tunnel $TunnelName"
& $Cloudflared tunnel route dns --overwrite-dns $TunnelName $Hostname
if ($LASTEXITCODE -ne 0) {
    throw "DNS route failed. Ensure the apex domain for '$Hostname' is in this Cloudflare account."
}

$publicUrl = "https://$Hostname"
Set-Content -Path $UrlFile -Value $publicUrl -Encoding utf8

$envFile = Join-Path $ProjectRoot ".env.local-prod"
if (Test-Path $envFile) {
    $found = $false
    $newLines = foreach ($line in Get-Content $envFile) {
        if ($line -match '^FRONTEND_BASE_URL=') {
            $found = $true
            "FRONTEND_BASE_URL=$publicUrl"
        }
        else { $line }
    }
    if (-not $found) { $newLines = @($newLines) + "FRONTEND_BASE_URL=$publicUrl" }
    Set-Content -Path $envFile -Value $newLines -Encoding utf8
    Write-Step "Set FRONTEND_BASE_URL=$publicUrl in .env.local-prod"
}

# Persist hostname for ensure/start scripts
$stateFile = Join-Path $ConfigDir "tunnel-state.json"
@{
    tunnelName = $TunnelName
    tunnelId   = $tunnelId
    hostname   = $Hostname
    publicUrl  = $publicUrl
    configFile = $ConfigFile
    mode       = "named"
} | ConvertTo-Json | Set-Content -Path $stateFile -Encoding utf8

Write-Step "Named tunnel ready"
Write-Host "Public URL : $publicUrl/seim/"
Write-Host "Config     : $ConfigFile"
Write-Host "Next       : .\scripts\start-cloudflare-tunnel.ps1"
Write-Host ""
Write-Host "FRONTEND_BASE_URL was updated in .env.local-prod. Recreate web if it is already running:"
Write-Host "  docker compose -p seim-localprod -f docker-compose.local-prod.yml --env-file .env.local-prod up -d --force-recreate --no-deps web"
