# Generated by Django 5.2.3 on 2025-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, default='View Details', help_text='Text for the action button/link', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Direct link to the related resource (e.g., application detail page)', max_length=500, null=True),
        ),
    ]
