# Generated by Django 5.2.3 on 2025-11-11 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_action_text_notification_action_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('application_deadline', 'Application Deadline'), ('document_deadline', 'Document Deadline'), ('program_start', 'Program Start'), ('program_end', 'Program End'), ('custom', 'Custom Reminder')], help_text='Type of event to remind about', max_length=50)),
                ('event_id', models.UUIDField(help_text='ID of the related object (Program, Application, etc.)')),
                ('event_title', models.CharField(help_text='Title/description of the event', max_length=255)),
                ('remind_at', models.DateTimeField(help_text='When to send the reminder')),
                ('sent', models.BooleanField(default=False, help_text='Whether the reminder has been sent')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='Category for styling and priority', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category'], name='notif_category_idx'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notification',
            field=models.ForeignKey(blank=True, help_text='Notification created when reminder was sent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'sent'], name='reminder_user_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['remind_at', 'sent'], name='reminder_time_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['event_type', 'event_id'], name='reminder_event_idx'),
        ),
    ]
